### ISSUE TITLE
Does not stop if error happens overwriting executable

### ISSUE THREAD

**Issue by estei** [DanskSupermarked/nvi#17]
If there is a running node process when you run nvi, the script does not stop running.
This has the unfortunate consequence that npm will be updated even if the node install fails.

Maybe we should detect errors and stop execution when detected.
An example of when this can happen is if we run nvi while node is already running, blocking nvi from overwriting the node executable.

**Comment by emiln** [comment]
That's definitely bad behavior. [The culprit](https://github.com/DanskSupermarked/nvi/blob/7328e34c7502c4e5f06fb0fc687db9944c4007fe/nvi#L152-L158) just seems to be sloppy exit code handling. This should be easily fixable, and should definitely be fixed.
