### ISSUE TITLE
Ability to change version while node is running

### ISSUE THREAD

**Issue by estei** [DanskSupermarked/nvi#18]
Related to #17

It would be great for local development if it was possible for us to use nvi to change node version while node is already running. 

This would allow us to for instance use nvi from  a script in `package.json`.
This fails because nvi tries to overwrite the node executable while it is running.

**Comment by emiln** [comment]
I totally agree. There's no conceptual or technical reason why this should be impossible. While it's not the core goal of `nvi` it's not in conflict with that goal either and would greatly increase usability.
