### ISSUE TITLE
It no werkz

### ISSUE THREAD

**Issue by estei** [DanskSupermarked/nvi#21]
The latest release seems to not work... it just exits without any input if you call nvi without any arguments hoping it will get the version from package.json

**Comment by emiln** [comment]
We should probably add this case to our test suite. Since we have a broken version out at the moment, I'll opt to first fix that, however, and then have a look at overhauling the text suite later.

**Comment by emiln** [comment]
This should be fixed with release 1.0.2. Please see if that's true.

**Comment by estei** [comment]
I can confirm that it now werkz which is wonderful.
thank you for your hard work :-)
