### ISSUE TITLE
Does not pass ShellCheck

### ISSUE THREAD

**Issue by commonquail** [DanskSupermarked/nvi#4]
[ShellCheck](https://github.com/koalaman/shellcheck) is a well-regarded shell script linter. `nvi` has a few violations spread around, all trivial to solve; they are mostly about quoting.

ShellCheck is straight-forward to hook up in Travis, too.

Interested?

**Comment by emiln** [comment]
I read that as two questions.

**Are we interested in adhering to ShellCheck?**

Yes, that sounds good to me. I think it's fair to categorize most of us as Bash novices in need of help. If ShellCheck is a well-renowned standard, then let's use that.

**Are we interested in a Travis CI setup?**

Perhaps. After a year or so with GitLab I don't really know the state of the various CI/CD tools out there. The question is mostly whether Travis is the right choice. There's no doubt that we want to hook up with _some_ CI/CD tooling.

Are you planning to create a PR yourself?

**Comment by commonquail** [comment]
Yes, yes, and yes.

Travis exclusively as a function of this project being GitHub-hosted. ShellCheck is available for every mainstream distro so any containerized CI would work.

**Comment by emiln** [comment]
With commit 52549f2d926ff70681b6eeb111618ca7816f09fe this is no longer an issue.
