### ISSUE TITLE
Improvements to Bash form

### ISSUE THREAD

**Issue by commonquail** [DanskSupermarked/nvi#5]
`[` and `function` are not good Bash form, c.f. [GreyCat's wiki](http://mywiki.wooledge.org/BashPitfalls). Neither is `echo` but that's more controversial. I don't yet know if there are other Bash-specific issues not already covered by #4.

**Comment by emiln** [comment]
I have implicit faith in GreyCat and their strong opinions on Bash. I'd be fine with a PR addressing the mentioned points.
