### ISSUE TITLE
Dense lines cause VCS churn

### ISSUE THREAD

**Issue by commonquail** [DanskSupermarked/nvi#6]
`nvi` has a few dense lines. While these are unlikely to change much going forward, addressing #4 and #5 will result in some noise. Lines can be broken down with `\`. I would have done this to start with but I'm not entirely sure it's worthwhile after the fact. I propose submitting a fix for #4 without breaking down lines and you can decide which is more tolerable.

**Comment by commonquail** [comment]
Here's a quick demonstration of now vs. broken down lines:

```diff
-    wget --output-document=$DOWNLOAD_DIR/$NODE_VERSION.tar.gz --quiet $NODE_TAR
+    wget --output-document="$DOWNLOAD_DIR/$NODE_VERSION.tar.gz" --quiet "$NODE_TAR"
```
```diff
-    tar --extract --file $DOWNLOAD_DIR/$NODE_VERSION.tar.gz --gzip --directory $INSTALL_DIR
+    tar --extract --file "$DOWNLOAD_DIR/$NODE_VERSION.tar.gz" --gzip --directory "$INSTALL_DIR"
```

```diff
     wget --quiet \
-      --output-document=$DOWNLOAD_DIR/$NODE_VERSION.tar.gz \
-      $NODE_TAR
+      --output-document="$DOWNLOAD_DIR/$NODE_VERSION.tar.gz" \
+      "$NODE_TAR"
```
```diff
     tar --extract --file \
-      $DOWNLOAD_DIR/$NODE_VERSION.tar.gz \
+      "$DOWNLOAD_DIR/$NODE_VERSION.tar.gz" \
       --gzip \
-      --directory $INSTALL_DIR
+      --directory "$INSTALL_DIR"
```

You can see that the noise is more localized but certainly does not disappear, and for the specific case of quoting it hardly performs better than `git diff --word-diff-regex=.`.

**Comment by emiln** [comment]
I think this is down to the level of a _Bash style guide_ in that it doesn't influence behavior at all. I'm open to the idea, but I would rather pick a style guide and then change the styling than the other way around. Do you have a fully-fledged style guide as the basis for these suggestions?

**Comment by commonquail** [comment]
Nope! I just tell people that more short lines are easier to diff than fewer long lines.

**Comment by emiln** [comment]
I don't think there's any disagreement about the virtues of adding line breaks in relation to `git diff`. I think the proposed changes are good, but mostly because I think they make the Bash code more readable. I'm very open to the changes being implemented, I just think the better argument is that is makes it less likely that a reader misses a flag when skimming the code, rather than `git diff` with no word diff specified looking better.

In either case we should implement the changes.
